<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>KOINKOIN  ->  Filtre</title>
	</head>
	<body>
		<h1>- FILTRES -</h1>
		<h2>- RECUPERER 1 VALEUR D'UN FILTRE XPATH D'1 SEULE PAGE WEB -</h2>		
		<?php
			echo "<p>"."Url : ".$_GET['url']."</p>";
			echo "<p>"."Filtre xpath utilise : ".$_GET['filtre']."/p>";
			echo "<p>"."Resultat : ".$_SESSION['resultat']."</p>";
			
		?>

	</body>
</html>
