<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>KOINKOIN</title>
<meta name="author" content="kkscrap">
</head>
<body>
	<h1>
		<a
			href="../">KOINKOIN</a>
		- maquette 1

	</h1>
	<h3>OBJECTIF</h3>
	<p>Scraper une URL_HTTPS pour obtenir un CONTENU_TEXTE_XPATH </p>
	<h3>DESCRIPTION</h3>
	<p>Cette maquette est un exemple concret de l'utilisation d'un filtre XPATH sur une page web (unique)</p>
	<p>Cette maquette scrape une page du site de petites annonces de LEBONCOIN, pour extraire le premier element de la liste principale (qui contient les titres des peites annonces</p>
	<h3>URL</h3>
	<p><?php echo $_SESSION ['koinkoin'] ['maquettes'] ['1'] ['config'] ['url_de_depart'] [0] ?></p>
	<h3>FILTRE XPATH</h3>
	<p>
	
	
	<pre><?php echo $_SESSION ['koinkoin'] ['maquettes'] ['1'] ['config'] ['filtre_xpath'] [0] ["pattern"] ?></pre>
	</p>

	<h3>RESULTAT XPATH</h3>
	<p><?php echo $_SESSION ['koinkoin'] ['maquettes'] [1] ['resultats'] ['match_xpath'] ?></p>

	<h3>SESSION</h3>

</body>
</html>

