<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>KOINKOIN</title>
<meta name="author" content="kkscrap">
</head>
<body>
	<h1>KOINKOIN</h1>
	<p>Koinkoin est un programme php/zend qui permet d'extraire du contenu
		sur le web</p>
	<p>Site internet : http://dreamproject.fr/koinkoin/public</p>
	<p>Github : https://github.com/kkscrap/koinkoin</p>
	<p>Wiki : http://dreamproject.fr/koinkoin/wiki</p>
	<p>Forum : http://dreamproject.fr/koinkoin/forum</p>
	<p>Mail : koinkoin-php@dreamproject.fr</p>
	<h2>MAQUETTES</h2>
	<ol>
		<li><a href='maquette/index'>Maquettes</a></li>
	</ol>
	<h2>ARCHIVES</h2>
	<ol>
		<li><a href='screenshot_tout_premier_screenshot_maquette_1.png'>20170318 ==> Maquette</a></li>
		<li><a href='http://dreamproject.fr/koinkoin/archives/screenshot_maquette_20170318.png'>20170315 ==> Maquette</a></li>
	</ol>
</body>
</html>
