<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>KOINKOIN</title>
<meta name="author" content="kkscrap">
</head>
<body>
	<h1>KOINKOIN</h1>
	<p>Koinkoin est un programme php/zend qui permet d'extraire du contenu
		sur le web</p>
	<p>Site internet : http://dreamproject.fr/koinkoin/public</p>
	<p>Github : https://github.com/kkscrap/koinkoin</p>
	<p>Wiki : http://dreamproject.fr/koinkoin/wiki</p>
	<p>Forum : http://dreamproject.fr/koinkoin/forum</p>
	<p>Mail : koinkoin-php@dreamproject.fr</p>
	<h2>MAQUETTES</h2>
	<ol>
		<li><a href='maquette/index'>Maquettes</a></li>
	</ol>
	<h2>MAQUETTES (archives)</h2>
	<ol>
		<li><a href='http://dreamproject.fr/koinkoin_20170315/public/index.php/scrap/maquette1'>Maquette 1 (20170315)</a></li>
	</ol>
</body>
</html>
