<?php $koinkoin314 = $this->koinkoin314;?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>KOINKOIN</title>
<meta name="author" content="kkscrap">
<style>
.dump {
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
	margin: 0 auto;
	text-align: left;
	padding: 5px;
	background-color: #f6f6f6;
	border: 1px dotted #d2d2d2;
	color: #666666;
	line-height: 20px;
	font-size: 11px;
	/* Pour avoir un retour à la ligne si la ligne dépasse la largeur du cadre */
	/*white-space: pre-wrap;
	white-space: -moz-pre-wrap;
	white-space: -pre-wrap;
	white-space: -o-pre-wrap;
	word-wrap: break-word;*/
	overflow-y: auto;
}

.dump .indentation {
	color: #dedede;
}

.dump .var {
	color: #000000;
	font-size: 24px;
	font-weight: normal;
	font-style: italic;
}

.dump .info-type {
	color: #e88046;
}

.dump .access {
	font-style: italic;
	color: #aaaaaa;
}

.dump .type {
	color: #aaaaaa;
}

.dump .equal {
	color: #457b7b;
	font-size: 12px;
	font-weight: bold;
}

.dump .bracket {
	color: #aaaaaa;
}

.dump .value {
	font-size: 14px;
}

.dump .value.string {
	color: #a52b2e;
}

.dump .value.string .hellip {
	font-size: 15px;
	font-weight: bold;
}

.dump .value.string .hellip .hellip {
	font-size: 17px;
}

.dump .value.int {
	color: #06a50d;
}

.dump .value.bool {
	color: #861486;
}

.dump .value.float {
	color: #185fa6;
}

.dump .value.empty {
	color: #808080;
}

.dump .value.null {
	color: #d2cc6d;
}

.dump .info-string {
	color: #bbbbbb;
	font-style: italic;
}

ul.krumo-node {
	margin: 0px;
	padding: 0px;
}

ul.krumo-node ul {
	margin-left: 20px;
}

* html ul.krumo-node ul {
	margin-left: 24px;
}

div.krumo-root {
	border: solid 1px black;
	margin: 1em 0em;
}

ul.krumo-first {
	font: normal 12px arial;
	border: solid 2px white;
	border-top-width: 1px;
	background: url(%url%bg.gif);
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
li.krumo-child {
	display: block;
	list-style: none;
	padding: 0px;
	margin: 0px;
	overflow: hidden;
}

div.krumo-element {
	cursor: default;
	line-height: 24px;
	display: block;
	clear: both;
	white-space: nowrap;
	border-top: solid 1px white;
	background: #FCEBA9;
	padding-left: 10px;
}

* html div.krumo-element {
	padding-bottom: 3px;
}

a.krumo-name {
	color: #404000;
	font: bold 13px Arial;
}

a.krumo-name big {
	font: bold 20pt Georgia;
	line-height: 14px;
	position: relative;
	top: 2px;
	left: -2px;
}

* html a.krumo-name big {
	font: bold 19pt Georgia;
	top: 5px;
	left: 0px;
	line-height: 9px;
	height: 12px;
	padding: 0px;
	margin: 0px;
}

div.krumo-expand {
	background: #FADB61;
	cursor: pointer;
}

div.krumo-hover {
	background: #FF8A4B;
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
div.krumo-preview {
	font: normal 13px courier new;
	padding: 5px 5px 14px 5px;
	background: white;
	border-top: 0px;
	overflow: auto;
}

* html div.krumo-preview {
	padding-top: 2px;
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
li.krumo-footnote {
	background: white;
	padding: 2px 5px;
	list-style: none;
	border-top: solid 1px #bebebe;
	margin-top: 2px;
	cursor: default;
}

* html li.krumo-footnote {
	line-height: 13px;
}

div.krumo-version {
	float: right;
}

li.krumo-footnote h6 {
	font: bold 11px verdana;
	margin: 0px;
	padding: 0px;
	color: #E87400;
	display: inline;
}

* html li.krumo-footnote h6 {
	margin-right: 3px;
}

li.krumo-footnote a {
	font: bold 10px arial;
	color: #434343;
	text-decoration: none;
}

li.krumo-footnote a:hover {
	color: black;
}

li.krumo-footnote span.krumo-call {
	font: normal 11px verdana;
	position: relative;
	top: 1px;
}

li.krumo-footnote span.krumo-call code {
	font-weight: bold;
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
div.krumo-title {
	font: normal 11px verdana;
	position: relative;
	top: 9px;
	cursor: default;
	line-height: 2px;
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */
strong.krumo-array-length, strong.krumo-string-length {
	font-weight: normal;
}
</style>
</head>
<body class="dump">


	<script>

  /**
  * JavaScript routines for Krumo
  *
  * @version $Id: krumo.js 22 2007-12-02 07:38:18Z Mrasnika $
  * @link http://sourceforge.net/projects/krumo
  */

  /////////////////////////////////////////////////////////////////////////////

  /**
  * Krumo JS Class
  */
  function krumo() {
  	}

  // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

  /**
  * Add a CSS class to an HTML element
  *
  * @param HtmlElement el 
  * @param string className 
  * @return void
  */
  krumo.reclass = function(el, className) {
  	if (el.className.indexOf(className) < 0) {
  		el.className += (' ' + className);
  		}
  	}

  // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

  /**
  * Remove a CSS class to an HTML element
  *
  * @param HtmlElement el 
  * @param string className 
  * @return void
  */
  krumo.unclass = function(el, className) {
  	if (el.className.indexOf(className) > -1) {
  		el.className = el.className.replace(className, '');
  		}
  	}

  // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

  /**
  * Toggle the nodes connected to an HTML element
  *
  * @param HtmlElement el 
  * @return void
  */
  krumo.toggle = function(el) {
  	var ul = el.parentNode.getElementsByTagName('ul');
  	for (var i=0; i<ul.length; i++) {
  		if (ul[i].parentNode.parentNode == el.parentNode) {
  			ul[i].parentNode.style.display = (ul[i].parentNode.style.display == 'none')
  				? 'block'
  				: 'none';
  			}
  		}

  	// toggle class
  	//
  	if (ul[0].parentNode.style.display == 'block') {
  		krumo.reclass(el, 'krumo-opened');
  		} else {
  		krumo.unclass(el, 'krumo-opened');
  		}
  	}

  // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

  /**
  * Hover over an HTML element
  *
  * @param HtmlElement el 
  * @return void
  */
  krumo.over = function(el) {
  	krumo.reclass(el, 'krumo-hover');
  	}

  // -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

  /**
  * Hover out an HTML element
  *
  * @param HtmlElement el 
  * @return void
  */

  krumo.out = function(el) {
  	krumo.unclass(el, 'krumo-hover');
  	}
  	
  /////////////////////////////////////////////////////////////////////////////
  
  </script>


	<img src="./images/koinkoin_logo.jpg" />
	<h1 class="var">DUMP_DD</h1>
	<!-- 	<p></p> -->
	<!-- 	<p> -->
	<!-- 		==> <a href='https://github.com/kkscrap/koinkoin'>Koinkoin sur Github</a> -->
	<!-- 	</p> -->
	<!-- 	<p> -->
	<!-- 		==> <a href='http://dreamproject.fr/koinkoin/wiki'>Wiki</a> -->
	<!-- 	</p> -->
	<!-- 	<p> -->
	<!-- 		==> <a href='http://dreamproject.fr/koinkoin/forum'>Forum de -->
	<!-- 			discussion</a> -->
	<!-- 	</p> -->
	<!-- 	<h2> -->
	<!-- 		<a href='./../maquettes/'>MAQUETTES</a> -->
	<!-- 	</h2> -->
	<!-- 	<h2 class="var">ARCHIVES</h2> -->
	<!-- 	<ol> -->
	<!-- 		<li><a -->
	<!-- 			href='../../archives/screenshot_tout_premier_screenshot_maquette_1.png'>20170315 -->
	<!-- 				==> Screenshot (dump)</a></li> -->
	<!-- 		<li><a href='../../archives/screenshot_maquette_20170318.png'>20170318 -->
	<!-- 				==> Screenshot (2eme dump)</a></li> -->
	<!-- 		<li><a href='../../archives/'>20170318 ==> AUTRES ARCHIVES</a></li> -->
	<!-- 	</ol> -->
	<!-- 	<h1>DUMP_KRUMO (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_krumo->dump_krumos ();
?>
	<h4>session -> kksmaquettes [ kks_maquettes ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_maquettes']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>

	<h4>session -> kksurls [ kks_urls ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_urls']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>

	<h4>session -> kksxpath [ kks_xpath ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_xpath']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>

	<h4>session -> kksregex [ kks_regex ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_regex']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>

	<h4>session -> kksscripts [ kks_scripts ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_scripts']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>

	<h4>session -> kkstidy [ kks_tidy ]</h4>
	<?php
$kksession = new \Zend_Session_Namespace('kks_library');
$kksession->dump_dd->dump_dd($_SESSION['kks_tidy']);
?>
<!-- 	<h1>DUMP_MARCOU (session)</h1> -->
	<?php
// $kksession = new \Zend_Session_Namespace ( 'kks_library' );
// $kksession->dump_marcou->dump_marcou ( $_SESSION );
?>


	<?php
?>

</p>


</body>
</html>
