<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>KOINKOIN</title>
<meta name="author" content="kkscrap">
<style>
.dump {
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
	margin: 0 auto;
	text-align: left;
	padding: 5px;
	background-color: #f6f6f6;
	border: 1px dotted #d2d2d2;
	color: #666666;
	line-height: 20px;
	font-size: 13px;
	/* Pour avoir un retour à la ligne si la ligne dépasse la largeur du cadre */
	/*white-space: pre-wrap;
	white-space: -moz-pre-wrap;
	white-space: -pre-wrap;
	white-space: -o-pre-wrap;
	word-wrap: break-word;*/
	overflow-y: auto;
}

.dump .indentation {
	color: #dedede;
}

.dump .var {
	color: #000000;
	font-size: 24px;
	font-weight: normal;
	font-style: italic;
}

.dump .info-type {
	color: #e88046;
}

.dump .access {
	font-style: italic;
	color: #aaaaaa;
}

.dump .type {
	color: #aaaaaa;
}

.dump .equal {
	color: #457b7b;
	font-size: 12px;
	font-weight: bold;
}

.dump .bracket {
	color: #aaaaaa;
}

.dump .value {
	font-size: 14px;
}

.dump .value.string {
	color: #a52b2e;
}

.dump .value.string .hellip {
	font-size: 15px;
	font-weight: bold;
}

.dump .value.string .hellip .hellip {
	font-size: 17px;
}

.dump .value.int {
	color: #06a50d;
}

.dump .value.bool {
	color: #861486;
}

.dump .value.float {
	color: #185fa6;
}

.dump .value.empty {
	color: #808080;
}

.dump .value.null {
	color: #d2cc6d;
}

.dump .info-string {
	color: #bbbbbb;
	font-style: italic;
}
</style>
</head>
<body class="dump">
	<h1 class="var">
		<a href="http://dreamproject.fr/koinkoin/public/index.php">KOINKOIN</a> - maquette 1

	</h1>
	<h3 class="var">OBJECTIF</h3>
	<p><?php echo $_SESSION ['koinkoin314']  ['configuration_maquettes'] [0] ['objectif']?></p>
	<h3 class="var">DESCRIPTION</h3>
	<?php
	
	foreach ( $_SESSION ['koinkoin314'] ['configuration_filtres'] [0] ["description"] as $description_filtre ) {
		echo "<p>" . $description_filtre . "</p>";
	}
	?>
	<h3 class="var">URLS DE DEPART</h3>
	<?php
	foreach ( $_SESSION ['koinkoin314'] ['configuration_filtres'] [0] ['urls_de_depart'] [0] ['url'] as $url_de_depart ) {
		echo "<p>" . $url_de_depart . "</p>";
	}
	?>
	<h3 class="var">FILTRE XPATH</h3>
	<p>
	
	
	<pre><?php echo $_SESSION ['koinkoin314']  ['configuration_filtres'] [0] ["pattern"] ?></pre>
	</p>

	<h3 class="var">RESULTAT XPATH</h3>
	<p><?php echo $_SESSION ['koinkoin314'] ['resultats_filtres'] [0] ['match_xpath'] ?></p>

	<h3 class="var">SESSION (DD_DUMP)</h3>
	<p><?php echo $_SESSION ['koinkoin314'] ['library_dump'] ['dd_dump']->dump_dd_dump ( $_SESSION ); ?></p>

	<h3 class="var">SESSION (PHP_DUMP_MARCOU)</h3>
	<p><?php echo $_SESSION ['koinkoin314'] ['library_dump'] ['php_dump_marcou']->php_dump_marcou ( $_SESSION ); ?></p>







</body>
</html>

