<div id="zone_milieu_1">
	<p id="titre">Releases</p>
	<ul>
		<li><a href="http://127.0.0.1/projects/KOINKOIN/public/index/releases">Releases</a></li>
	</ul>
	<h3>Filtres</h3>
	<ul>
		<li><a
			href="http://127.0.0.1/projects/KOINKOIN/public/filtre?methode=uneUrlunFiltre&filtre=.//*[@id=%27listingAds%27]/section/section/ul/li[2]/a/section/h2&url=https://www.leboncoin.fr/offres_d_emploi/offres/ile_de_france/?th=1">Filtre
				: 1 url 1 filtre Xpath</a></li>
	</ul>
</div>