<?php
	echo '<!doctype html>'."\n";
	echo '<html>'."\n";
	echo '	<head>'."\n";
	echo '		<title>'.$_SESSION['projet']['nom'].' - '.$_SESSION['projet']['version'].'</title>'."\n";
	echo '	</head>'."\n";
	echo '	<body>'."\n";
	echo '		<div id="zone_haut">'."\n";
	echo '			<h1>KOINKOIN V001</h1>'."\n";
	echo '			<h2>MAQUETTE POUR AMAURY</h2>'."\n";
	echo '		</div><!-- fin zone_haut -->'."\n";
	echo '		<div id=zone_milieu>'."\n";
	echo '			<h3>QUELQUES EXEMPLES ...</h3>'."\n";
	echo '			<h4>FILTRES XPATH</h4>'."\n";
	echo '			<ul>'."\n";
	echo '				<li><a href="http://127.0.0.1/KOINKOIN/public/maquette/ecran1">LEBONCOIN -> RAYON -> FILTRE XPATH -> récupérer le titre de la première petite annonce (ecran1)</a></li>'."\n";
	echo '				<li><a href="http://127.0.0.1/KOINKOIN/public/maquette/ecran1">LEBONCOIN -> RAYON -> FILTRE XPATH -> récupérer le titre de toutes les petites annonces (ecran2)</a></li>'."\n";
	echo '			</ul>'."\n";
	echo '			<h3>IHMS</h3>'."\n";
	echo '			<ul>'."\n";
	echo '				<li><a href="F:/[Tags]/Koinkoin/Formulaires formoid/v001/users___creer_un_utilisateur.html">user -> creer un utilisateur</a></li>'."\n";
	echo '				<li><a href="F:/[Tags]/Koinkoin/Formulaires%20formoid/v001/outils___importer_une_page_internet.html">outils -> importer une page web</a></li>'."\n";
	echo '			</ul>'."\n";
	echo '			<h3>NOTES</h3>'."\n";
	echo '			<ul>'."\n";
	echo "				<li>ECRAN1 -> url=https://www.leboncoin.fr/offres_d_emploi/offres/ -> filtrexpath=id('listingAds')/x:section/x:section/x:ul/x:li[2]</li>"."\n";
	echo '				<li><a href="F:/[Tags]/Koinkoin/Formulaires%20formoid/v001/outils___importer_une_page_internet.html">outils -> importer une page web</a></li>'."\n";
	echo '			</ul>'."\n";
	echo '		</div><!-- fin zone_milieu -->'."\n";
	echo '	</body>'."\n";
	echo '</html>'."\n";
	;
	
?>